#cloud-config
# DO NOT DELETE ABOVE LINE. It signals to the cloud-init program that this should be interpreted as a cloud-config file.
#
# These keys below belong to the "Package Update Upgrade Install" module.
# See http://cloudinit.readthedocs.io/en/latest/topics/modules.html#package-update-upgrade-install

packages: []

package_update: false
package_upgrade: false
package_reboot_if_required: false

final_message: "Boot completed in $UPTIME seconds"
